version: '3.3'
services:
  website:
    image: 'joseluisq/static-web-server:2-alpine'
    container_name: candina-me
    ports:
      - '8082:80'
    restart: unless-stopped
    environment:
      - SERVER_ROOT=/var/public
      - SERVER_CONFIG_FILE=/etc/sws.toml
    volumes:
      - './public:/var/public'
      - './sws.toml:/etc/sws.toml'