services:
  kamiyomu:
    image: marcoscostadev/kamiyomu:latest
    ports:
      - "7810:8080"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sync time with host
      - ${APP_DATA_DIR}/manga:/manga
      - ${APP_DATA_DIR}/db:/db
      - ${APP_DATA_DIR}/agents:/agents
      - ${APP_DATA_DIR}/logs:/logs