services:
  app_proxy:
    environment:
      APP_HOST: nginx_server_1
      APP_PORT: '8143'
      PROXY_AUTH_ADD: 'false'
    container_name: nginx_app_proxy_1
  web:
    image: nginx:alpine
    container_name: nginx_web_server
    ports:
      - "8143:80"
    volumes:
      - ${APP_DATA_DIR}/www:/usr/share/nginx/html:ro
    restart: unless-stopped
